apiVersion: v1
kind: Service
metadata:
  name: nest-ddd-service
spec:
  type: LoadBalancer
  selector:
    app: nest-ddd
  ports:
    - protocol: TCP
      port: 3000  # Expose the service on port 80
      targetPort: 3000  # Forward traffic to your application on port 3000
  
